# Compiler and flags
CXX = g++
CXXFLAGS = -std=c++11 -Wall -Wextra -lcurl

# Executable name
TARGET = deribit_client

# Source files
SRCS = main.cpp
OBJS = $(SRCS:.cpp=.o)

# Build the executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

# Compile the source files into object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -
